package com.dam.salesianostriana.di.trianadvisorv1.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.dam.salesianostriana.di.trianadvisorv1.greendao.Valoraciones;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VALORACIONES".
*/
public class ValoracionesDao extends AbstractDao<Valoraciones, Long> {

    public static final String TABLENAME = "VALORACIONES";

    /**
     * Properties of entity Valoraciones.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ObjectId = new Property(1, String.class, "objectId", false, "OBJECT_ID");
        public final static Property UpdateAt = new Property(2, String.class, "updateAt", false, "UPDATE_AT");
        public final static Property Valoracion = new Property(3, String.class, "valoracion", false, "VALORACION");
        public final static Property IdUsuarioV = new Property(4, long.class, "idUsuarioV", false, "ID_USUARIO_V");
        public final static Property IdSitioV = new Property(5, long.class, "idSitioV", false, "ID_SITIO_V");
    };

    private DaoSession daoSession;

    private Query<Valoraciones> usuarios_ValoracionesDeUnUsuarioQuery;
    private Query<Valoraciones> usuarios_ValoracionesDeUnSitioQuery;

    public ValoracionesDao(DaoConfig config) {
        super(config);
    }
    
    public ValoracionesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VALORACIONES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"OBJECT_ID\" TEXT," + // 1: objectId
                "\"UPDATE_AT\" TEXT," + // 2: updateAt
                "\"VALORACION\" TEXT," + // 3: valoracion
                "\"ID_USUARIO_V\" INTEGER NOT NULL ," + // 4: idUsuarioV
                "\"ID_SITIO_V\" INTEGER NOT NULL );"); // 5: idSitioV
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VALORACIONES\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Valoraciones entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        String updateAt = entity.getUpdateAt();
        if (updateAt != null) {
            stmt.bindString(3, updateAt);
        }
 
        String valoracion = entity.getValoracion();
        if (valoracion != null) {
            stmt.bindString(4, valoracion);
        }
        stmt.bindLong(5, entity.getIdUsuarioV());
        stmt.bindLong(6, entity.getIdSitioV());
    }

    @Override
    protected void attachEntity(Valoraciones entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Valoraciones readEntity(Cursor cursor, int offset) {
        Valoraciones entity = new Valoraciones( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // objectId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // updateAt
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // valoracion
            cursor.getLong(offset + 4), // idUsuarioV
            cursor.getLong(offset + 5) // idSitioV
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Valoraciones entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setObjectId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUpdateAt(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setValoracion(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIdUsuarioV(cursor.getLong(offset + 4));
        entity.setIdSitioV(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Valoraciones entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Valoraciones entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "valoracionesDeUnUsuario" to-many relationship of Usuarios. */
    public List<Valoraciones> _queryUsuarios_ValoracionesDeUnUsuario(long idUsuarioV) {
        synchronized (this) {
            if (usuarios_ValoracionesDeUnUsuarioQuery == null) {
                QueryBuilder<Valoraciones> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdUsuarioV.eq(null));
                queryBuilder.orderRaw("T.'ID_USUARIO_V' ASC");
                usuarios_ValoracionesDeUnUsuarioQuery = queryBuilder.build();
            }
        }
        Query<Valoraciones> query = usuarios_ValoracionesDeUnUsuarioQuery.forCurrentThread();
        query.setParameter(0, idUsuarioV);
        return query.list();
    }

    /** Internal query to resolve the "valoracionesDeUnSitio" to-many relationship of Usuarios. */
    public List<Valoraciones> _queryUsuarios_ValoracionesDeUnSitio(long idSitioV) {
        synchronized (this) {
            if (usuarios_ValoracionesDeUnSitioQuery == null) {
                QueryBuilder<Valoraciones> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdSitioV.eq(null));
                queryBuilder.orderRaw("T.'ID_SITIO_V' ASC");
                usuarios_ValoracionesDeUnSitioQuery = queryBuilder.build();
            }
        }
        Query<Valoraciones> query = usuarios_ValoracionesDeUnSitioQuery.forCurrentThread();
        query.setParameter(0, idSitioV);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUsuariosDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getSitiosDao().getAllColumns());
            builder.append(" FROM VALORACIONES T");
            builder.append(" LEFT JOIN USUARIOS T0 ON T.\"ID_USUARIO_V\"=T0.\"_id\"");
            builder.append(" LEFT JOIN SITIOS T1 ON T.\"ID_SITIO_V\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Valoraciones loadCurrentDeep(Cursor cursor, boolean lock) {
        Valoraciones entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Usuarios usuarios = loadCurrentOther(daoSession.getUsuariosDao(), cursor, offset);
         if(usuarios != null) {
            entity.setUsuarios(usuarios);
        }
        offset += daoSession.getUsuariosDao().getAllColumns().length;

        Sitios sitios = loadCurrentOther(daoSession.getSitiosDao(), cursor, offset);
         if(sitios != null) {
            entity.setSitios(sitios);
        }

        return entity;    
    }

    public Valoraciones loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Valoraciones> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Valoraciones> list = new ArrayList<Valoraciones>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Valoraciones> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Valoraciones> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
